# CMake generated Testfile for 
# Source directory: /Users/amirabouguera/SSLES/depends/ethsnarks/src/test
# Build directory: /Users/amirabouguera/SSLES/.build/ethsnarks/src/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(run_test_field2bits "/Users/amirabouguera/SSLES/.build/ethsnarks/src/test/test_field2bits")
set_tests_properties(run_test_field2bits PROPERTIES  _BACKTRACE_TRIPLES "/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;11;add_test;/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;0;")
add_test(run_test_field_packing "/Users/amirabouguera/SSLES/.build/ethsnarks/src/test/test_field_packing")
set_tests_properties(run_test_field_packing PROPERTIES  _BACKTRACE_TRIPLES "/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;11;add_test;/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;0;")
add_test(run_test_isnonzero "/Users/amirabouguera/SSLES/.build/ethsnarks/src/test/test_isnonzero")
set_tests_properties(run_test_isnonzero PROPERTIES  _BACKTRACE_TRIPLES "/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;11;add_test;/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;0;")
add_test(run_test_lookup_1bit "/Users/amirabouguera/SSLES/.build/ethsnarks/src/test/test_lookup_1bit")
set_tests_properties(run_test_lookup_1bit PROPERTIES  _BACKTRACE_TRIPLES "/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;11;add_test;/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;0;")
add_test(run_test_lookup_2bit "/Users/amirabouguera/SSLES/.build/ethsnarks/src/test/test_lookup_2bit")
set_tests_properties(run_test_lookup_2bit PROPERTIES  _BACKTRACE_TRIPLES "/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;11;add_test;/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;0;")
add_test(run_test_lookup_3bit "/Users/amirabouguera/SSLES/.build/ethsnarks/src/test/test_lookup_3bit")
set_tests_properties(run_test_lookup_3bit PROPERTIES  _BACKTRACE_TRIPLES "/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;11;add_test;/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;0;")
add_test(run_test_merkle_tree "/Users/amirabouguera/SSLES/.build/ethsnarks/src/test/test_merkle_tree")
set_tests_properties(run_test_merkle_tree PROPERTIES  _BACKTRACE_TRIPLES "/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;11;add_test;/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;0;")
add_test(run_test_mimc "/Users/amirabouguera/SSLES/.build/ethsnarks/src/test/test_mimc")
set_tests_properties(run_test_mimc PROPERTIES  _BACKTRACE_TRIPLES "/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;11;add_test;/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;0;")
add_test(run_test_mimc_hash "/Users/amirabouguera/SSLES/.build/ethsnarks/src/test/test_mimc_hash")
set_tests_properties(run_test_mimc_hash PROPERTIES  _BACKTRACE_TRIPLES "/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;11;add_test;/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;0;")
add_test(run_test_one_of_n "/Users/amirabouguera/SSLES/.build/ethsnarks/src/test/test_one_of_n")
set_tests_properties(run_test_one_of_n PROPERTIES  _BACKTRACE_TRIPLES "/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;11;add_test;/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;0;")
add_test(run_test_sha256_full_gadget "/Users/amirabouguera/SSLES/.build/ethsnarks/src/test/test_sha256_full_gadget")
set_tests_properties(run_test_sha256_full_gadget PROPERTIES  _BACKTRACE_TRIPLES "/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;11;add_test;/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;0;")
add_test(run_test_sha256_many "/Users/amirabouguera/SSLES/.build/ethsnarks/src/test/test_sha256_many")
set_tests_properties(run_test_sha256_many PROPERTIES  _BACKTRACE_TRIPLES "/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;11;add_test;/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;0;")
add_test(run_test_shamir_poly "/Users/amirabouguera/SSLES/.build/ethsnarks/src/test/test_shamir_poly")
set_tests_properties(run_test_shamir_poly PROPERTIES  _BACKTRACE_TRIPLES "/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;11;add_test;/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;0;")
add_test(run_test_subadd "/Users/amirabouguera/SSLES/.build/ethsnarks/src/test/test_subadd")
set_tests_properties(run_test_subadd PROPERTIES  _BACKTRACE_TRIPLES "/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;11;add_test;/Users/amirabouguera/SSLES/depends/ethsnarks/src/test/CMakeLists.txt;0;")
subdirs("jubjub")
subdirs("benchmark")
